### ISSUE TITLE
 ERROR: Deleting duplicate device name Dyson Pure Cool Link

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#237]
Krocko Hello. Can you please help me with this error?

```Jul 09 21:55:19 raspberrypi homebridge[14878]: [Alexa] ERROR: Deleting duplicate device name Dyson Pure Cool Link```

**Comment by NorthernMan54** [comment]
Root is the temperature service uses same name as on/off switch

**Comment by NorthernMan54** [comment]
Fixed, please update to the latest

**Comment by Krocko** [comment]
I updated to the latest version. Error message is gone but the device is still not visible in the alexa App.

**Comment by NorthernMan54** [comment]
When I run the accessory dump you shared a couple of months ago thru, I see this as the Alexa names

                    "friendlyName": "Bose SoundTouch 10",
                    "friendlyName": "Bose SoundTouch 20",
                    "friendlyName": "Bose SoundTouch 300",
                    "friendlyName": "Night Mode - Dyson Pure Cool Link",
                    "friendlyName": "Auto - Dyson Pure Cool Link",
                    "friendlyName": "Dyson Pure Cool Link Temperature Sensor",
                    "friendlyName": "Dyson Pure Cool Link",
                    "friendlyName": "RaspberryPi Info",
                    "friendlyName": "Homebase NAS",
                    "friendlyName": "Homebase NAS temperature",
                    "friendlyName": "Erfurt Temperature",

Try deleting any with "Dyson Pure Cool Link" and running discover again.

**Comment by Krocko** [comment]
Thank you. The Problem is solved with the latest Version.
