### ISSUE TITLE
100 Percent Issue

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#414]
Hello.  I'm having a strange issue. 

If I ask Alexa to set my light to 100 percent, it responds back saying the device doesn't support that.  I can however set it to anything between 1-98 percent. 

Is there a reason I can't do 100 percent and/or 99 percent?

Homekit works fine if I ask Siri to set the light to 100 percent.   Any thoughts?

**Comment by NorthernMan54** [comment]
This is pretty weird, can you try deleting the light from the Alexa app, then ask Alexa to discover devices.

**Comment by meluvalli** [comment]
It’s doing it to all my lights.  So are you saying just delete one and test
just one at a time?

**Comment by NorthernMan54** [comment]
Yeah, try it with one

**Comment by meluvalli** [comment]
Same result.  If I say Alexa, kitchen light 100%, it responds back “That
command doesn’t work on device kitchen light”.  Again, works if I do 98% or
lower.

**Comment by NorthernMan54** [comment]
What's your account on the cloud server ( you can DM me directly via discord if you want )

**Comment by jvmahon** [comment]
I'm cross-posting a link to the response I gave in my forum. See https://github.com/jvmahon/Homebridge-HomeSeer4/issues/136#issuecomment-766704366

**Comment by meluvalli** [comment]
Ok, for some reason 99 percent is now working with the Alexa one.  However, 100 percent still doesn't.  @NortherMan54 can you confirm should it work?  If you do 100 percent, should it know it is really 99 percent?  Is this a feasible change?

**Comment by NorthernMan54** [comment]
This should now be resolved

**Comment by meluvalli** [comment]
This still doesn't work.  "Alexa, Office Light 100%".  Response: "That command doesn't work on device Office Light".  Still have to say "Alexa, Office Light 99%" to turn light on fully.

**Comment by groove06** [comment]
Good day where ever you are. I have a problem with homebridge connected as a skill with Alexa- all device went unresponsive. Upon troubleshooting and removing some devices, Alexa will not rediscover. I have disabled/reenable the skill. I have uninstalled and reinstalled the plugin in HOOBS, to no avail.

**Comment by NorthernMan54** [comment]
@groove06 - Please don't jump on a different issue with a new issue

Have you checked your account dashboard on homebridge.ca ?

**Comment by groove06** [comment]
My apologies, I'm new to blogs. Used to just speaking to someone. What part did I jump on? Yes my dashboard reads green on all sections.

**Comment by NorthernMan54** [comment]
@groove06 Please open a new issue or reach out via the homebridge discord server to discuss
